spring.application.name=ai-code-reviewer

# AI config
app.ai.enabled=${APP_AI_ENABLED:true}
app.ai.api-key=${OPENAI_API_KEY:}
app.ai.model=${APP_AI_MODEL:gpt-5.4-mini}

# GitHub config
app.github.token=${GITHUB_TOKEN:}
app.github.api-base-url=https://api.github.com

# Cloud Run port
server.port=${PORT:8080}

# Do not expose stacktrace in browser
server.error.include-stacktrace=never
server.error.include-message=always